[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dark_protocol = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
privacy_pool = "PrivacyPool111111111111111111111111111111"
shielded_token = "ShieldToken111111111111111111111111111111"

[programs.devnet]
dark_protocol = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
privacy_pool = "PrivacyPool111111111111111111111111111111"
shielded_token = "ShieldToken111111111111111111111111111111"

[programs.mainnet]
dark_protocol = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
privacy_pool = "PrivacyPool111111111111111111111111111111"
shielded_token = "ShieldToken111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/dark-protocol",
    "programs/privacy-pool",
    "programs/shielded-token"
]
